# Site settings
title: Pablo Monteserín
email: pablomonteserin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Pablomon's portfolio
baseurl:  /
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  pablomon

# Build settings
markdown: kramdown
# markdown: GFM

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  projects:
    output: true
    permalink: /projects/:path/


plugins: [jekyll-paginate]